name: Deploy to Github Pages
on:
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 8
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: Install NPM dependencies
        run: npm install
      - name: Test App
        env:
          CI: true
        run: npm run test
      - name: Build
        if: success()
        env:
          PUBLIC_URL: /SENSO-Trail-App/
        run: npm run build
      - name: PostBuild
        if: success()
        env:
          PUBLIC_URL: /SENSO-Trail-App/
        run: bash fixMapSourcesForGithubPages.sh
      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./build
